# Generated by Django 5.0 on 2024-01-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid_app', '0001_initial'),
        ('routes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyramid',
            name='routes',
            field=models.ManyToManyField(blank=True, null=True, to='routes_app.route'),
        ),
    ]
