# Generated by Django 5.0 on 2024-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid_app', '0002_alter_pyramid_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyramid',
            name='location',
            field=models.CharField(default='unkown'),
        ),
    ]
