# Generated by Django 5.0 on 2024-01-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid_app', '0003_pyramid_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyramid',
            name='location',
            field=models.CharField(default='unknown'),
        ),
    ]
