# Generated by Django 5.0 on 2024-01-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid_app', '0005_alter_pyramid_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyramid',
            name='location',
            field=models.CharField(blank=True, default='unknown', null=True),
        ),
    ]
