# Generated by Django 5.0 on 2024-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid_app', '0006_alter_pyramid_location'),
        ('routes_app', '0006_alter_route_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyramid',
            name='routes',
            field=models.ManyToManyField(to='routes_app.route'),
        ),
    ]
