# Generated by Django 5.0 on 2024-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid_app', '0008_alter_pyramid_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyramid',
            name='goal_grade',
            field=models.CharField(),
        ),
    ]
