# Generated by Django 5.0 on 2024-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_route',
            name='data_id',
            field=models.CharField(max_length=255),
        ),
    ]
