# Generated by Django 5.0 on 2024-01-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0002_alter_favorite_route_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_route',
            old_name='data_id',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='favorite_route',
            name='data_type',
        ),
        migrations.AddField(
            model_name='favorite_route',
            name='areaName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite_route',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
