# Generated by Django 5.0 on 2023-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('area', models.CharField()),
                ('completed', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=255)),
            ],
        ),
    ]
