# Generated by Django 5.0 on 2024-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='media',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
