# Generated by Django 5.0 on 2024-01-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0002_alter_route_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='area',
            field=models.CharField(null=True),
        ),
    ]
