# Generated by Django 5.0 on 2024-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0003_alter_route_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
