# Generated by Django 5.0 on 2024-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0004_alter_route_lat_alter_route_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(default='notaclimb', max_length=255),
        ),
    ]
