# Generated by Django 5.0 on 2024-01-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0005_alter_route_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(default='notaclimb', max_length=255, null=True),
        ),
    ]
