# Generated by Django 5.0 on 2024-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0006_alter_route_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='areaid',
            field=models.CharField(null=True),
        ),
    ]
