# Generated by Django 5.0 on 2024-03-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0007_route_areaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_id',
            new_name='uuid',
        ),
    ]
