# Generated by Django 5.0 on 2024-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0008_rename_route_id_route_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='mp_id',
            field=models.CharField(null=True),
        ),
    ]
