# Generated by Django 5.0 on 2024-02-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticked_Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('mountain_id', models.CharField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('areaName', models.CharField(max_length=255, null=True)),
                ('date_ticked', models.DateTimeField(auto_now_add=True)),
                ('style', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
