# Generated by Django 5.0 on 2024-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks_app', '0002_ticked_route_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticked_route',
            name='style',
            field=models.CharField(blank=True, null=True),
        ),
    ]
