# Generated by Django 5.0 on 2024-02-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks_app', '0003_alter_ticked_route_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticked_route',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticked_route',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticked_route',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
