# Generated by Django 5.0 on 2024-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks_app', '0005_ticked_route_lat_ticked_route_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticked_route',
            name='date_ticked',
            field=models.DateTimeField(),
        ),
    ]
