# Generated by Django 5.0 on 2024-02-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticks_app', '0006_alter_ticked_route_date_ticked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticked_route',
            name='rating',
        ),
    ]
