# Generated by Django 5.0 on 2023-12-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_user_current_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.IntegerField(null=True),
        ),
    ]
