# Generated by Django 5.0 on 2024-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0006_alter_route_route_id'),
        ('user_app', '0004_rename_location_user_lat_user_long_alter_user_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticks',
            field=models.ManyToManyField(blank=True, to='routes_app.route'),
        ),
    ]
