# Generated by Django 5.0 on 2024-02-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_user_ticks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_level',
        ),
    ]
