# Generated by Django 5.0 on 2024-02-21 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_user_current_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ticks',
        ),
        migrations.AddField(
            model_name='user',
            name='ticks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
